Fixed the functionnality of the Carousel.
CybercentreCanada/assemblyline-ui-frontend pull request #266
Opened 2022-03-16 20:01 UTC by cccs-nr

- Aligned the Close button to the right.
 - Escape keydown now closes the Carousel.
 - Opening the carousel now properly focuses it.
 - Fixed a bug where closing the carousel would instantly close instead of doing its animation like the opening.

2022-03-17 11:38 UTC, gdesmar approved these changes

2022-03-17 18:54 UTC, cccs-sgaron requested changes
Can you please rebase your branch on the current master and create the appropriate PR for master?

2022-03-18 13:35 UTC, cccs-nr commented
Is this correctly rebased ?

2022-03-21 12:40 UTC, cccs-sgaron commented
> Is this correctly rebased ?

Your PR to master looks legit so I'd assume yes.

2022-03-21 19:55 UTC, merged